<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Total recall)

| **Term** | **Brief description** |
| :----- | :---------------------: |
| Subsetting | Subsetting is used to identify whether certain elements are found in an array |
| Indexing | *Indexing means to select one element from a sequence using its position* |
| Slicing | Slicing is used to select a range of elements from a sequence |
| Masking | Masking is to hide certain values in an array |

# Exercise 2 (Show me the 'odd' letters)

In [4]:
import numpy as np

In [100]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [107]:
first_elements = np_array_2d[:,0]
print(first_elements)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


In [125]:
first_elements = first_elements.astype(int) %2 != 0

In [127]:
print(np_array_2d[first_elements,1])

['A' 'C' 'E' 'G' 'I']


# Exercise 3 

In [84]:
np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [90]:
np_array[np_array < 50] = -1

In [91]:
np_array[np_array > 50] = +1

In [92]:
np_array[np_array == 50] = 0

In [93]:
print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
