<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [5]:
import numpy as np

np.float(64) means characters go up to 64, float is owned by numpy


# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

### Python Lists


In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]


In [6]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [8]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]


In [11]:
py_super_names[1] = 'ildsgfilsddjhdh'

In [12]:
np_super_names

array(['Black Widow', 'Iron Man', 'Doctor Strange'], dtype='<U14')

### Example 1 

In [16]:
py_super_names[-1]

'Doctor Strange'

In [17]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

## 1.3 Accessing data from a dictionary

In [18]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

## 1.4 Higher dimensional lists

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [24]:
superhero_info = {
    "Natasha Romanoff": "Marvel",
    "Tony Stark": "Marvel",
    "Stephen Strange": "Marvel"
}                  

# 2 Lists vs. Arrays

In [23]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J","Hahahah"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [34]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J', 'Hahahah']]

In [35]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

In [31]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J","Hahahah"]]
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J', 'Hahahah']]

## 2.1 Size

In [28]:
len(py_list_2d)   #len gives you the number of rows in a table 

10

In [29]:
len(np_array_2d)

10

In [33]:
'hahaha'.upper()

'HAHAHA'

In [32]:
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type


In [36]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

## 2.3 Adding a number

### List

In [37]:
py_list

[1, 1.5, 'A']

### Arrays

In [38]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.4 Adding another list

In [48]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

### List

In [49]:
py_list+[10]

[1, 2, 3, 4, 5, 10]

### Arrays

In [43]:
np_array + 10 


array([11, 12, 13, 14, 15])

In [52]:
np_array ** 2

array([ 1,  4,  9, 16, 25])

## 2.5 Multiplying by a Number

### List

In [ ]:
py_list = [1, 2, 3, 4, 5]      

In [72]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

### Arrays 

In [ ]:
np_array = np.array(py_list)  

In [73]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

### List

In [74]:
py_list = [1, 2, 3, 4, 5]

In [75]:
py_list**2  # Will not work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### Arrays

In [76]:
np_array = np.array(py_list)

In [77]:
np_array**2


array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [56]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [55]:
py_list == 3   


False

In [58]:
np_array == 3

array([False, False,  True, False, False])

In [57]:
np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [59]:
py_list = [1,2,3,4,5]
np_array = np.array(py_list)

In [60]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function

np.float64(1.4142135623730951)

In [62]:
sum(np_array)

np.int64(15)

In [67]:
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

In [71]:
sum(py_list)

15

## Footnotes