<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [2]:
import numpy as np

# 1 Subsetting: Indexing and Slicing

In python, every list starts with 0 

In [3]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [6]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [5]:
x[2:8:2]

array(['c3', 'e5', 'g7'], dtype='<U3')

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

## 1.2 Arrays only | Subsetting by masking

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_name = (np_array > 3) & (np_array < 8) # Use brackets to separate
np_array[~my_name] # ~ represents no

array([ 1,  2,  3,  8,  9, 10])

In [18]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_name = (np_array > 3) | (np_array < 8)
np_array[my_name]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np_array[my_name]

array([4, 5, 6, 7])

In [12]:
np_array[1:4]

array([2, 3, 4])

In [14]:
my_name.sum()

np.int64(4)

In [17]:
np_array[1:3]

array([2, 3])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [20]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)


In [25]:
py_list_2d[3][1]

'D'

In [23]:
np_array_2d[3,1]

np.str_('D')

## 1.4 Growing lists

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes